### ISSUE TITLE
Add script to enable module on a target Safe

### ISSUE THREAD

**Issue by fleupold** [cowdao-grants/cow-fee#12]
We will likely have to enable/disable the module periodically (on every keeper rotation, in case someone wants to run the script manually with their own key, etc).

It would be nice to have a single script that someone can run from an owner account to propose a transaction that enables this module on a target safe.

**Comment by fleupold** [comment]
This is just to "propose" the transaction to the wallet (for this some teams use a dedicated proposer account, which is shared and doesn't count as a real signer). I would the review and signing assume to happen via the UI (using whatever properly secured keys signers use)

You can see https://github.com/cowprotocol/contracts/blob/main/src/tasks/withdraw/safe.ts#L36 for reference

**Comment by mfw78** [comment]
I see it's already done (the 8cd3f853899bba3f9e31850e70629edb70bf776e already pushed), but in general, given the likely frequency this would be used, I'd think having guidance on how to use `cast` to generate the calldata that is required in order to enable / disable the module so that this could be inserted into the transaction builder would be simple enough (reasoning: reduced dependencies, reduced code base, simpler).

**Comment by meetmangukiya** [comment]
If already using the transaction builder on safe UI, there is also a more direct way to add or remove module on the safe settings page
